apiVersion: v1
kind: Pod
metadata:
  name: kiada-ssl                                
spec:
  containers:
  - name: kiada                                  #A
    image: luksa/kiada:0.2                       #A
    ports:                                       #A
    - name: http                                 #A
      containerPort: 8080                        #A
  - name: envoy                                  #B
    image: luksa/kiada-ssl-proxy:0.1             #B
    ports:                                       #B
    - name: https                                #B
      containerPort: 8443                        #B
    - name: admin                                #B
      containerPort: 9901                        #B